version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      # or specify the runtime you need (python, java, etc.)
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y curl unzip
  build:
    commands:
      - echo Build started on `date`
      - echo Building the project...
artifacts:
  files:
    - '**/*'

