version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - apt-get update
      - apt-get install -y build-essential
  build:
    commands:
      - echo Build started on `date`
      - make build  # or your custom build command
artifacts:
  files:
    - '**/*'

